%Explicit solutions for system 4.2
function [c,p] = sys_4_2_sol(t, mu_pc_mem, p0, lambda_taup_mem, lambda_pp_mem, r_tau, c0)
c = c0 - (mu_pc_mem*p0 - (lambda_taup_mem*mu_pc_mem*r_tau)/lambda_pp_mem)...
    /lambda_pp_mem + (exp(-lambda_pp_mem*t)*(mu_pc_mem*p0 - ...
    (lambda_taup_mem*mu_pc_mem*r_tau)/lambda_pp_mem) - ...
    lambda_taup_mem*mu_pc_mem*r_tau*t)/lambda_pp_mem;
p = (lambda_taup_mem*r_tau + exp(-lambda_pp_mem*t)*(lambda_pp_mem*p0 - lambda_taup_mem*r_tau))/lambda_pp_mem;

end